before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  - echo "Restoring NuGet Packages..."
  - '"src\nuget\NuGet.exe" restore "GiteaVS.sln"'
 
stages:
  - buildGiteaForVS
buildGiteaForVS:
  stage: buildGiteaForVS
  script:
  -  rebuildself.cmd    GiteaVS.sln
 
  artifacts:
    expire_in: 2 mos
    name: "%CI_PROJECT_NAME%_%CI_COMMIT_REF_NAME%"
    paths:
    -  build/Release/Gitea.VisualStudio.vsix
    -  README.md
    
 